export const ADD_PAGE = 'ADD_PAGE'

export const FETCH_SECTION_REQUEST = 'FETCH_SECTION_REQUEST'
export const FETCH_SECTION_SUCCESS = 'FETCH_SECTION_SUCCESS'
export const FETCH_SECTION_FAILURE = 'FETCH_SECTION_FAILURE'
