export const RECENT_FETCH_REQUEST = 'posts/RECENT_FETCH_REQUEST'
export const RECENT_FETCH_SUCCESS = 'posts/RECENT_FETCH_SUCCESS'
export const RECENT_FETCH_FAILURE = 'posts/RECENT_FETCH_FAILURE'

export const TRENDING_FETCH_REQUEST = 'posts/TRENDING_FETCH_REQUEST'
export const TRENDING_FETCH_SUCCESS = 'posts/TRENDING_FETCH_SUCCESS'
export const TRENDING_FETCH_FAILURE = 'posts/TRENDING_FETCH_FAILURE'

export const POPULARS_FETCH_REQUEST = 'posts/POPULARS_FETCH_REQUEST'
export const POPULARS_FETCH_SUCCESS = 'posts/POPULARS_FETCH_SUCCESS'
export const POPULARS_FETCH_FAILURE = 'posts/POPULARS_FETCH_FAILURE'
